/*
 * Brady Reed
 * Umass Lowell INFO3010
 */
package bradyreed.view;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

import bradyreed.baseclasses.Classroom;
import bradyreed.baseclasses.Classroom.Room;

import bradyreed.model.ClassroomDataModel;
/**
 *
 * @author brady
 */
public class InputClassroomInfo extends javax.swing.JFrame {
    
    private ClassroomDataModel classroomdatamodel;
    
    /**
     * Creates new form ClassroomInputFormUsingNetbeans
     */
    
    public InputClassroomInfo(ClassroomDataModel classroomDataModelArg) {
        initComponents();
        // Set Size after creating
        this.setSize(400, 175);

        this.classroomdatamodel = classroomDataModelArg;
        
        // Create a data model that will hold all the enumerated room types
        DefaultComboBoxModel roomTypeList = new DefaultComboBoxModel(Room.values());

        // Once we have the data model we can link it to the list on the form
        roomTypeCombobox.setModel(roomTypeList);
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomNumberLabel = new javax.swing.JLabel();
        roomTypeLabel = new javax.swing.JLabel();
        roomNumberTextfield = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        roomTypeCombobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        roomNumberLabel.setText("Room Number:");
        getContentPane().add(roomNumberLabel);
        roomNumberLabel.setBounds(30, 20, 120, 14);

        roomTypeLabel.setText("Room Type:");
        getContentPane().add(roomTypeLabel);
        roomTypeLabel.setBounds(30, 60, 100, 14);
        getContentPane().add(roomNumberTextfield);
        roomNumberTextfield.setBounds(130, 20, 100, 30);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(40, 100, 100, 23);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(150, 100, 90, 23);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(250, 100, 90, 23);

        roomTypeCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLASSROOM", "LECTURE_HALL", "LAB"}));
        getContentPane().add(roomTypeCombobox);
        roomTypeCombobox.setBounds(130, 60, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.roomNumberTextfield.setText("");
        this.roomTypeCombobox.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Create a new classroom object
            Classroom aClassroom = new Classroom();

            // Retrieve the values from the form
            String roomNumber = this.roomNumberTextfield.getText();
            
            // Add exception handling here

            
            // The value must come from the drop down list of string values and converted to a Room and Room value
            
            // Step 1 - Retrieve the data model associated with the combo list box
            ComboBoxModel comboboxdatamodel = this.roomTypeCombobox.getModel();
            // Step 2 - Retrieve the selected item
            Object selectedItem = comboboxdatamodel.getSelectedItem();
            // Step 3 - Convert (Cast) the selected item to a Room object
            Classroom.Room roomType = Classroom.Room.valueOf(selectedItem.toString());
            // Step 4 - Use the Classroom setters to set the values
            aClassroom.setRoomNumber(roomNumber);
            aClassroom.setTypeOfRoom(roomType);

            // Add to the list in the data model
            this.classroomdatamodel.getListOfClassrooms().add(aClassroom);
//            System.out.println("Save was successfull");
//            System.out.println(classroomdatamodel.getListOfClassrooms().get(1).toString());
            this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed
    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputClassroomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputClassroomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputClassroomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputClassroomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        ClassroomDataModel classroomDataModelTest = new ClassroomDataModel();
        Classroom testRoom = new Classroom("999", Classroom.Room.LAB);
        classroomDataModelTest.getListOfClassrooms().add(testRoom);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputClassroomInfo(classroomDataModelTest).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JTextField roomNumberTextfield;
    private javax.swing.JComboBox<String> roomTypeCombobox;
    private javax.swing.JLabel roomTypeLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}




